In [64]:
import numpy as np

x = np.random.randint(0,10,(1,10))
print(x)
y=np.transpose(x)
print(y)
print(x*y)


[[5 2 1 3 4 2 2 7 6 0]]
[[5]
 [2]
 [1]
 [3]
 [4]
 [2]
 [2]
 [7]
 [6]
 [0]]
[[25 10  5 15 20 10 10 35 30  0]
 [10  4  2  6  8  4  4 14 12  0]
 [ 5  2  1  3  4  2  2  7  6  0]
 [15  6  3  9 12  6  6 21 18  0]
 [20  8  4 12 16  8  8 28 24  0]
 [10  4  2  6  8  4  4 14 12  0]
 [10  4  2  6  8  4  4 14 12  0]
 [35 14  7 21 28 14 14 49 42  0]
 [30 12  6 18 24 12 12 42 36  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [117]:
A=np.add(*np.indices((5,5)))
A

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [155]:
arr= np.arange(0,10)
arr= np.tile(arr,(10,1))
print(arr,'\n')
arr=arr.reshape(-1,10)
print(np.transpose(arr))
np.transpose(arr) +arr

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]] 

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [156]:
np.transpose(np.tile(np.arange(0,5),(5,1)).reshape(-1,5)) + np.tile(np.arange(0,5),(5,1))


array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [157]:
np.transpose(arr) +arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [176]:
from numpy.linalg import inv
[[1,2],[3,3]] * inv([[1 ,2],[3 ,3]])

array([[-1.        ,  1.33333333],
       [ 3.        , -1.        ]])